# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      ImageFullName: registry.cn-hangzhou.aliyuncs.com/sigeer/lottery_machine
      VersionName: 9.1

    steps:
    - uses: actions/checkout@v3

    - name: Login
      run: docker login -u${{secrets.DOCKERUNAME}} -p${{secrets.DOCKERPASSWORD}} registry.cn-hangzhou.aliyuncs.com

    - name: Build Image
      run: docker build -t "$ImageFullName:$VersionName" -t "$ImageFullName:latest" -f ./src/LotteryMachine.Web/Dockerfile ./src

    - name: Assert
      run: docker images

    - name: Push Latest
      run: docker push "$ImageFullName:latest"

    - name: Push Version
      run: docker push "$ImageFullName:$VersionName"
